### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'uri')

### ISSUE THREAD

**Issue by Ya2gLu** [ebeaufay/3DTilesViewer#3] opened 2021-09-18 08:28 UTC
I am replaced with my own path in the index.js file:
![image](https://user-images.githubusercontent.com/48912522/133882090-fb9722e5-c25d-481d-abcc-029e6cf27f95.png)

The result is an error in the loader.js file:
![image](https://user-images.githubusercontent.com/48912522/133882130-ffa05091-7303-4d68-aa11-ad8a1f5808c0.png)

This is the TileSet.json format I have:
![image](https://user-images.githubusercontent.com/48912522/133882283-616d3dcc-bbad-426d-8448-0eb2b2714cdc.png)

Is it a problem with the structure?

**Comment by ebeaufay** [comment] 2021-09-18 09:36
The part of the Json you shared looks fine. Can you check that further down that you don't have an empty "content" object? If so, it might be that the parser fails in that case.

I can check in the 3dtiles spec if this is actually allowed but I propose the lib should support empty "content" regardless.

**Comment by Ya2gLu** [comment] 2021-09-18 09:52
I checked my JSON file and found that there is no empty "content" object.

It seems that it doesn't seem this problem ...

**Comment by ebeaufay** [comment] 2021-09-18 12:10
Ok, if you can share the tileset I will fix

**Comment by ebeaufay** [comment] 2021-09-21 06:43
if you can only share the tileset.json file, that can be enough

**Comment by Ya2gLu** [comment] 2021-09-22 00:36
{
    "asset": {
        "gltfUpAxis": "Z",
        "version": "0.0"
    },
    "geometricError": 1570.6053466796875,
    "root": {
        "boundingVolume": {
            "box": [
                -1781972.25,
                4594572,
                4037342.5,
                625.625,
                0,
                0,
                0,
                370.75,
                0,
                0,
                0,
                296.375
            ]
        },
        "children": [
            {
                "boundingVolume": {
                    "box": [
                        -1781594.25,
                        4594814,
                        4037139,
                        165.125,
                        0,
                        0,
                        0,
                        128.75,
                        0,
                        0,
                        0,
                        88.875
                    ]
                },
                "content": {
                    "uri": "BlockXYXY/tileset.json"
                },
                "geometricError": 457.9215393066406,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781568.125,
                        4594739,
                        4037284,
                        162.625,
                        0,
                        0,
                        0,
                        127.75,
                        0,
                        0,
                        0,
                        85.625
                    ]
                },
                "content": {
                    "uri": "BlockXYXB/tileset.json"
                },
                "geometricError": 446.03009033203125,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781843.5,
                        4594724,
                        4037142.75,
                        143.9375,
                        0,
                        0,
                        0,
                        126.75,
                        0,
                        0,
                        0,
                        96.5
                    ]
                },
                "content": {
                    "uri": "BlockXYAY/tileset.json"
                },
                "geometricError": 425.4996032714844,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781814.75,
                        4594650,
                        4037290.5,
                        136.625,
                        0,
                        0,
                        0,
                        108.25,
                        0,
                        0,
                        0,
                        75.5
                    ]
                },
                "content": {
                    "uri": "BlockXYAB/tileset.json"
                },
                "geometricError": 387.3284912109375,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781534.5,
                        4594651.5,
                        4037402.25,
                        153.9375,
                        0,
                        0,
                        0,
                        114,
                        0,
                        0,
                        0,
                        75.25
                    ]
                },
                "content": {
                    "uri": "BlockXBXY/tileset.json"
                },
                "geometricError": 409.3159484863281,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781503.25,
                        4594564,
                        4037539.5,
                        156.6875,
                        0,
                        0,
                        0,
                        125.75,
                        0,
                        0,
                        0,
                        89.5
                    ]
                },
                "content": {
                    "uri": "BlockXBXB/tileset.json"
                },
                "geometricError": 399.83447265625,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781777.875,
                        4594560,
                        4037403.5,
                        137.5,
                        0,
                        0,
                        0,
                        106.75,
                        0,
                        0,
                        0,
                        74.125
                    ]
                },
                "content": {
                    "uri": "BlockXBAY/tileset.json"
                },
                "geometricError": 388.8614501953125,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781740.875,
                        4594464,
                        4037536,
                        141.625,
                        0,
                        0,
                        0,
                        117.25,
                        0,
                        0,
                        0,
                        87.625
                    ]
                },
                "content": {
                    "uri": "BlockXBAB/tileset.json"
                },
                "geometricError": 404.9519348144531,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782011.5,
                        4594627,
                        4037181.75,
                        110.375,
                        0,
                        0,
                        0,
                        137.25,
                        0,
                        0,
                        0,
                        133.75
                    ]
                },
                "content": {
                    "uri": "BlockAYXX/tileset.json"
                },
                "geometricError": 410.4445495605469,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782153,
                        4594579,
                        4037185,
                        116,
                        0,
                        0,
                        0,
                        141.25,
                        0,
                        0,
                        0,
                        136.125
                    ]
                },
                "content": {
                    "uri": "BlockAYXA/tileset.json"
                },
                "geometricError": 413.73773193359375,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782308.25,
                        4594535,
                        4037195.5,
                        122.25,
                        0,
                        0,
                        0,
                        145,
                        0,
                        0,
                        0,
                        137.75
                    ]
                },
                "content": {
                    "uri": "BlockAYAX/tileset.json"
                },
                "geometricError": 392.1373596191406,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782471.75,
                        4594479,
                        4037199,
                        126.0625,
                        0,
                        0,
                        0,
                        142.75,
                        0,
                        0,
                        0,
                        134.25
                    ]
                },
                "content": {
                    "uri": "BlockAYAA/tileset.json"
                },
                "geometricError": 412.6789855957031,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782000.5,
                        4594492.5,
                        4037377.75,
                        129.75,
                        0,
                        0,
                        0,
                        109,
                        0,
                        0,
                        0,
                        83.25
                    ]
                },
                "content": {
                    "uri": "BlockABXY/tileset.json"
                },
                "geometricError": 407.01611328125,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1781962.25,
                        4594394.5,
                        4037540,
                        135.1875,
                        0,
                        0,
                        0,
                        123,
                        0,
                        0,
                        0,
                        98.875
                    ]
                },
                "content": {
                    "uri": "BlockABXB/tileset.json"
                },
                "geometricError": 349.2254333496094,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782155.625,
                        4594389,
                        4037456.5,
                        116.625,
                        0,
                        0,
                        0,
                        154.25,
                        0,
                        0,
                        0,
                        157
                    ]
                },
                "content": {
                    "uri": "BlockABAX/tileset.json"
                },
                "geometricError": 440.6132507324219,
                "refine": "REPLACE"
            },
            {
                "boundingVolume": {
                    "box": [
                        -1782365.5,
                        4594350,
                        4037424.5,
                        167.1875,
                        0,
                        0,
                        0,
                        148.75,
                        0,
                        0,
                        0,
                        118.625
                    ]
                },
                "content": {
                    "uri": "BlockABAA/tileset.json"
                },
                "geometricError": 465.4755554199219,
                "refine": "REPLACE"
            }
        ],
        "geometricError": 1570.6053466796875,
        "refine": "REPLACE"
    }
}

**Comment by Ya2gLu** [comment] 2021-09-22 02:09
This is my JSON file link:
[tileset.json](https://gitee.com/ya2glu/picgo_bed/raw/master/img/tileset.json)

**Comment by Ya2gLu** [comment] 2021-09-22 02:13
In addition, there is a directory structure of my file
![image](https://user-images.githubusercontent.com/48912522/134272759-a1b326b8-9aaa-49e6-848a-a1c921d97fad.png)

**Comment by ebeaufay** [comment] 2021-09-22 10:16
Ok, the issue is fixed. the code didn't support an empty root tile without a "content" object.

Try it out and don't forget to play around with "setGeometricErrorMultiplier" if the performance is bad.

Not sure what the tiling scheme is in the other jsons. 
For example in the folder BlockABAA, do you have several levels of detail?

If you want, I have code to re-tile the entire dataset from OBJ to optimal tiles. However I don't give this code out but I can process your dataset for you.

**Comment by Ya2gLu** [comment] 2021-09-23 02:03
yes, i see

I need to convert the OSGB format to B3DM. But the directory structure and you don't seem different...

Do you have any way?🙏🙏

**Comment by ebeaufay** [comment] 2021-09-25 05:32
I think "osgconv" can convert your osgb files to obj. 
Download the openSceneGraph binaries here (http://www.openscenegraph.org/index.php/download-section/stable-releases and run for every file : osgconv model.osg model.obj

If your dataset is small (less than 100mb) just load the highest level of detail OBJs in threejs directly. Else, you can send them to me and I can convert them to optimal 3dtiles. 

How about the 3dtiles you have now, did the fix work?

**Comment by ebeaufay** [comment] 2021-10-10 06:22
closing issue if no more comments

**Closed** 2021-10-10 06:34 UTC
